In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np;
np.array([1,2,3])

array([1, 2, 3])

In [12]:
a1=np.array([1,2,3,4,5,6,7,8,9,0]);
c=2
a1b=np.array([1,2,3,4,5,6,7,8,0]);
a2=np.array([[1,2,3,4,5,6],[1,2,3,4,5,6],[45,55,66,55,44,6]]);
a3=np.array([[[111,2,3,4,5],[1,2,3,4,5]],[[2,3,4,5,6],[3,4,4,5,5]]])
a4=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
a1+c

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11,  2])

In [ ]:
 
a1b.shape

(9,)

To get the length of the array

In [6]:
a1b+a2[1,1]

array([ 3,  4,  5,  6,  7,  8,  9, 10,  2])

Arrading the a1b[1]//2 wwith a2[1]//[1,2,3,4,5,6]

In [ ]:
a2[1]

array([1, 2, 3, 4, 5])

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [70]:
a1.ndim


1

In [75]:

a2.ndim

2

In [76]:
a3.ndim

3

ndim used to get the dimention of the array

In [82]:
a3[0,0,0]

111

#slicing

In [83]:
a1[:3]

array([1, 2, 3])

starts from 0 index and end before 3

In [111]:
a4[0,:2]

array([1, 2])

In [8]:
a2.ndim
a2

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [45, 55, 66, 55, 44]])

In [116]:
a2.sum(axis=0)

array([47, 59, 72, 63, 54])

sum the 2d array value from column wise // axis=0 mentoning sum the column

In [117]:
a2.mean(axis=1)

array([ 3.,  3., 53.])

find the mean value for each row

installing package numpy